import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <span className="font-bold text-3xl underline">Hello</span>
          <Link href="/">Home</Link>
          <Link href="/search">Search</Link>
          {children}
        </main>
      </body>
    </html>
  );
}
