import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { AstroScripts } from "../integrations/astro/astro-scripts";
import { RoutingProvider } from "../integrations/web-fragments/routing-provider";
import { Navbar } from "../modules/layout/navbar";
import "./globals.css";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className="bg-base-200" data-fragment="true" data-theme="dark">
        <div className="flex h-screen w-screen flex-col-reverse md:flex-row">
          <Navbar />
          <main className="w-full max-w-full overflow-x-hidden">
            {children}
          </main>
        </div>
        <AstroScripts />
        <RoutingProvider />
      </body>
    </html>
  );
}
